### PR TITLE
Page 353 Create English.txt

### PR DESCRIPTION
**Pull request by Isharfoxat**

### CODE REVIEW

**Comment by ryanvilbrandt** [comment]
Does this provide an update to what's already displayed on the main website? If not, you don't need to recreate the English transcript

**Comment by Isharfoxat** [comment]
No, it doesn't.
If providing an English.txt to GitHub is not needed nor useful, that's OK with me :)

**Comment by ryanvilbrandt** [comment]
If the transcript that's already on the website is correct, the only benefit of having the transcripts uploaded here as well is that it might give some plaintext versions for other translators to go off of. But I'm not a translator, so I don't know if that is actually helpful.

Since you've already done the work to create these transcripts, I'm happy to leave it up to you about whether you'd like to see them merged into the repo, or if we should just close the PRs. Let me know what you'd prefer.

**Comment by Isharfoxat** [comment]
Well, if it can help others, let's do this!
I personally found having the English version available useful, especially with the markdown formatting. I don't know how the others translators work, but if this bit of extra work can help, I'd say it's worth it.

**Comment by ryanvilbrandt** [comment]
I'm merging your English PRs now, as I agree that it's useful enough and harmless enough to be worthwhile. I'll also update the README with instructions for how anyone can get access to the Markdown version of the English transcript for any live page.

**Pull request merged**
