### PR TITLE
Created Deutsch.txt

### PR DESCRIPTION
**Pull request by Araxxas**
Hi, just translated the first page into German. Looking forward to work my way through 270 pages... oh my, what have I started? lol... I am all new to GitHub, so I am thankful for every hint and advise on improvements on how I can work on this more efficiently.

First question: how can I edit a file once I saved it to the branch? "Edit file" and "Delete file" are greyed out...

### CODE REVIEW

**Comment by ryanvilbrandt** [comment]
When you created your first file, GitHub made a fork of this repository for you at https://github.com/Araxxas/tamberlane-transcripts/

To edit a file after a PR (like this one) has been created, you'll need to go to your own forked version of the repository, find the branch that file is on, and edit it there. 

So for example, if you wanted to edit the file you've created in this PR, you'll want to go to `patch-1` branch. You can see all the branches on your repo by going to https://github.com/Araxxas/tamberlane-transcripts/branches/active

Then, find the file you want to edit, click on it, and you should see a pencil icon which should be clickable for you. That will let you edit the file.

**Comment by Araxxas** [comment]
Hi Ryan,
before I create more translated transcripts, I want to sort things out a bit. Therefore, I have a few more questions:

First question:
Is it correct that every time I add a file, a new branch is created from "Cvilbrandt/Tamberlane-transcripts"?
In my case: patch-1, patch-2, patch-3 etc... This seems not right to me. Can't I just add a new file to the "master" branch of "Araxxas/tamberlane-transcripts" and create a PullRequest for every single file I newly created there?
IF that is the case: can I clean up my mess and move or copy the files I already created in the "patch-xx" to the "master" branch, and afterwards delete the "patch-xx" branches?

Second question:
Is there a way to have the folders being sorted alphanumerically (1,2,3,...,10,11,12,...) instead of numeric sorting (1,11,12,..,100,2,21,...)? Its very hard for me to navigate through the folders like this.
Isn't it possible to (automatically?) rename the folders to 0001,0002,0003,...,0269,0270? 

Sorry to keep bugging you...

**Comment by ryanvilbrandt** [comment]
> First question:
> Is it correct that every time I add a file, a new branch is created from "Cvilbrandt/Tamberlane-transcripts"?
> In my case: patch-1, patch-2, patch-3 etc... This seems not right to me. 

This is what will happen if you create a file in GitHub in the cvilbrandt version of the repository. 

> Can't I just add a new file to the "master" branch of "Araxxas/tamberlane-transcripts" and create a PullRequest for every single file I newly created there?
> IF that is the case: can I clean up my mess and move or copy the files I already created in the "patch-xx" to the "master" branch, and afterwards delete the "patch-xx" branches?

Yup! As long as you edit the files in your own repository, this should absolutely be doable. I did a quick test to confirm back when I first looked into your comments, but please let me know if you have any issues with that.

> Second question:
> Is there a way to have the folders being sorted alphanumerically (1,2,3,...,10,11,12,...) instead of numeric sorting > (1,11,12,..,100,2,21,...)? Its very hard for me to navigate through the folders like this.
> If not, isn't it possible to (automatically?) rename the folders to 0001,0002,0003,...,0269,0270?

Unfortunately, GitHub doesn't allow for changing how the folders are sorted. Which, I agree, is very annoying. And changing the folder names will need to be done both in this repo and on the tamberlane comic site simultaneously. Which may be done eventually, but as far as I know, Caytlin doesn't have plans for it yet.

That said, I can say for certain that viewing your repository on your local PC (at least on Windows) does sort the folders correctly. If you download your repository with GitHub Desktop (https://desktop.github.com/) you should be able to make all the changes you want on your master branch, from own computer, in whatever text editor you want. And then make a single Pull Request for all of them at once.

**Comment by Araxxas** [comment]
Hi Ryan,
sorry for the long delay. But I just turned 46 years old, I have family and a job that requires my full attention (and energy) sometimes ;-)

I decided to change my file upload procedure and clean up the mess I made. I created a directory on my PC and copied all the files I translated so far therein.
I will now delete all of the branches I created, except for this one.
Then, I upload the files manually to the corresponding folders in this branch- just like I proposed to do on Aug 21st.

**Comment by ryanvilbrandt** [comment]
> Hi Ryan,
> sorry for the long delay. But I just turned 46 years old, I have family and a job that requires my full attention (and energy) sometimes ;-)
> 
> I decided to change my file upload procedure and clean up the mess I made. I created a directory on my PC and copied all the files I translated so far therein.
> I will now delete all of the branches I created, except for this one.
> Then, I upload the files manually to the corresponding folders in this branch- just like I proposed to do on Aug 21st.

No worries! These transcripts are fully volunteer-driven, and we appreciate any amount of time and effort you can provide to help keep them up to date. :)

I also have a full-time job outside of Tamberlane, so I sympathize greatly with spare time being a precious commodity.

**Pull request closed without merging**
