### PR TITLE
Create עברית

### PR DESCRIPTION
**Pull request by Catwellkatz**
A Hebrew translation project

### CODE REVIEW

**Comment by ryanvilbrandt** [comment]
You will want to add ".txt" to the end of this file for it to be picked up by the website. And it may be worth it to add the translation for "Chapter 1" to the file as well. Up to you.

**Comment by Catwellkatz** [comment]
Thank you, it will be noticed.
    On Tuesday, 13 February 2024 at 02:48:47 GMT+2, Ryan Vilbrandt ***@***.***> wrote:  
 
 


You will want to add ".txt" to the end of this file for it to be picked up by the website. And it may be worth it to add the translation for "Chapter 1" to the file as well. Up to you.

**Comment by ryanvilbrandt** [comment]
Since this PR is over a month old at this point, I'm closing it. Please feel free to recreate it when you've corrected the filename.

**Comment by Catwellkatz** [comment]
Fine, I'll let you know when I'm finished translating anything (until the point I'll stop in), and then I'll submit a pull request/

**Pull request closed without merging**
