### PR TITLE
Ukranian.txt

### PR DESCRIPTION
**Pull request by Auro442**

### CODE REVIEW

**Comment by ryanvilbrandt** [comment]
It looks like this file conflicts with another that got merged in more recently. https://github.com/cvilbrandt/tamberlane-transcripts/blob/master/8/Ukranian.txt

Which one is the correct translation? If the one already in the `master` branch is the correct one, please close this PR.

**Comment by Auro442** [comment]
The first translation is more correct.

**Comment by ryanvilbrandt** [comment]
Which one is the first translation? Is it the one in this PR? Or the one that's up on the website right now?

**Comment by Auro442** [comment]
Yes, it's the one in this PR.

**Pull request merged**
