### PR TITLE
Typo corrections on pages 14 and 34, first part of chapter 3 (p.100-150)

### PR DESCRIPTION
**Pull request by Araxxas**
Hi Ryan,

thanks to your help, this time it should work.
Instead of just creating a pull request, I added the first part of my translations of chapter 3, too.

I am not making progress as fast as in the beginning, because I have too much fun editing Caytlin's original comic pages (she allowed me to do so). I sent her an invitation to take a look at the first 25 pages, but I know she was sick AND busy, so I don't mind getting no response yet. If you want to, you can take a look yourself. I prepared a PDF and saved it to my Google Drive:
https://drive.google.com/drive/folders/12tkpbkH9BaekuOJqmFJAYDDb3e1cUZiZ?usp=sharing

Well then, it's 8p.m. over here, time to hit the couch and chill.
Bye, stay healthy, greetings to Caytlin

Oliver

### CODE REVIEW

**Comment by Araxxas** [comment]
Hi Ryan,
just wanted to pop a champagne bottle. 150 pages done! 🥳
Already merged into my master branch, you can merge it with your master branch if you want to.
I forgot to mention you on my last pull request two weeks ago, so may have not noticed it. 

Bye, stay healthy, greetings to Caytlin
Oliver

@ryanvilbrandt

**Comment by Araxxas** [comment]
Hi Ryan, 
just wanted to wish you a happy new year and check if you are still alive. ^^
Just kidding, I suppose you are just busy with other stuff. If not, and there's a problem with my transcripts,
drop a note here. 
Hope to hear from you,
greetings
Oliver

@ryanvilbrandt

**Comment by BomberBeetle** [comment]
merged :D happy new year!

**Comment by ryanvilbrandt** [comment]
Thanks for handling that @BomberBeetle!

Sorry for the wait, @Araxxas. Still not sure why I'm not getting reliably notified. I'll poke around at my email settings, but in the meantime @BomberBeetle also has permissions to merge PRs.

**Pull request merged**
